### ISSUE TITLE
Nullable properties need to be handled

### ISSUE THREAD

**Issue by da3dsoul** [maxpiva/Nancy.Rest.Module#2]
```
ErrorPipeline.Invoke => Bootstrapper.<RequestStartup>b__3_1 => Bootstrapper.onError Nancy Error => Request URL: http://127.0.0.1:8111/v1/TvDB/CrossRef/11831/1/1/303730/1/13/{crossRef_AniDB_TvDBV2ID}
ErrorPipeline.Invoke => Bootstrapper.<RequestStartup>b__3_1 => Bootstrapper.onError System.Exception: {crossRef_AniDB_TvDBV2ID is not a valid value for Int32. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s, NumberStyles style, IFormatProvider provider)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.NullableConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(Object value)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , TypeConverter , Object )
   at Nancy.Rest.Module.RestModule.GetParametersFromDynamic(RouteCacheItem ci, MethodInfo minfo, Object data, CancellationToken token) in C:\Users\mpiva\Documents\GIT\Nancy.Rest\Nancy.Rest.Module\RestModule.cs:line 307
   at Nancy.Rest.Module.RestModule.Route(Object cls, RouteCacheItem ci, Object d) in C:\Users\mpiva\Documents\GIT\Nancy.Rest\Nancy.Rest.Module\RestModule.cs:line 256
   at Nancy.Rest.Module.RestModule.<>c__DisplayClass13_0.<MapRoute>b__1(Object o) in C:\Users\mpiva\Documents\GIT\Nancy.Rest\Nancy.Rest.Module\RestModule.cs:line 75
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by maxpiva** [comment]
Done in 1.4.3.6
